version: "3.3"

services:
  write:
    image: comworkio/shmwrapper:latest-arm
    container_name: shmwrapper_write_arm
    ipc: host
    command: ["/shmwrapper", "-w", "foo", "bar"]
  read:
    image: comworkio/shmwrapper:latest-arm
    container_name: shmwrapper_read_arm
    ipc: host
    command: ["/shmwrapper", "-r", "foo"]
    depends_on:
      - write
